# Generated by Django 4.0.8 on 2024-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews_qty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_qty',
            field=models.IntegerField(blank=True),
        ),
    ]
