# Generated by Django 4.0.8 on 2024-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_price_alter_course_reviews_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
